version: "3.9"
services:
  desafio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio    
    environment:
      NODE_ENV: prod     
      DEFAULT_LOGIN: letscode
      DEFAULT_PASSWORD: lets@123 
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:3000:3000"
volumes:
  logvolume01: {}